Signet support
synonymdev/react-native-ldk pull request #138
Opened 2023-06-28 10:00 UTC by Jasonvdb

- Signet support
- Added `currencyString()` func to Kotlin to match iOS and return a string in the invoice object
- Small refactor to align kotlin and swift

2023-06-28 18:23 UTC, coreyphillips requested changes

2023-06-28 18:23 UTC, coreyphillips commented on lib/android/src/main/java/com/reactnativeldk/Helpers.kt
> +        Currency.LDKCurrency_Signet -> "Simnet"
Duplicate.

2023-06-28 21:34 UTC, bennyhodl commented
`lib/src/utils/helpers.ts`:
`startParamCheck()` needs to have signet

`example/utils/helpers.ts`:
`ldkNetwork()` needs to have signet 👍

2023-06-28 22:02 UTC, bennyhodl commented
All looks good when I added the changes above. I used https://github.com/synonymdev/react-native-ldk/pull/135 to test signet on [mutiny net](https://mutinynet.com).

Did find that bitcoinjs does not support signet. So I was only able to test adding a peer and opening a channel. Application crashes on get script pubkey history.

2023-06-29 00:26 UTC, bennyhodl commented
Getting an error after the channel is confirmed in the Native setTxConfirmed. All info passed into looks correct

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })', src/c_types/mod.rs:438:116
stack backtrace:
```

2023-06-29 07:55 UTC, Jasonvdb commented
@bennyhodl maybe try this? https://github.com/bitcoinjs/bitcoinjs-lib/issues/1820#issuecomment-1193400719

2023-06-29 20:54 UTC, bennyhodl commented
Params for `NativeLDK.setTxConfirmed()`

```
{
"header":"00000020139124db0d9d6146337157757b8312ea5356be78657ce2f49048a4079e000000cb2185d2859fdb659b6b15095f525ec217b451dbfaee47531d51f3072cf6cd988bbc9c64ae77031e6c6c0c00", 
"height": 195433, 
"transaction": "87e7e6c3012e8b2ee49aa4006dd39a40b8ffea9fb29323a2ede71a85fa522f7e", "vout": [{"hex": "00207776e80733beeeab67f22f3f8dbf6dd267c31a338c02181003babc92356a092e", "n": 0, "value": 1000000}, {"hex": "51204e13bbdc2ccbf8b6e9db49308d00bf717220256bb622e99b259a523c768f7902", "n": 1, "value": 7999690}]}
```

transaction: https://mutinynet.com/tx/87e7e6c3012e8b2ee49aa4006dd39a40b8ffea9fb29323a2ede71a85fa522f7e

block: https://mutinynet.com/block/000001fa4c271b5b335782836949d67c7a4d250b94eb51944407c42b8fe9be6f

2023-06-30 07:33 UTC, Jasonvdb commented
> 



> {
> "header":"00000020139124db0d9d6146337157757b8312ea5356be78657ce2f49048a4079e000000cb2185d2859fdb659b6b15095f525ec217b451dbfaee47531d51f3072cf6cd988bbc9c64ae77031e6c6c0c00", 
> "height": 195433, 
> "transaction": "87e7e6c3012e8b2ee49aa4006dd39a40b8ffea9fb29323a2ede71a85fa522f7e", "vout": [{"hex": "00207776e80733beeeab67f22f3f8dbf6dd267c31a338c02181003babc92356a092e", "n": 0, "value": 1000000}, {"hex": "51204e13bbdc2ccbf8b6e9db49308d00bf717220256bb622e99b259a523c768f7902", "n": 1, "value": 7999690}]
> }

Looks like the wrong format and native can't parse it. Are you calling `NativeLDK.setTxConfirmed` directly? If you are rather call `ldk.setTxConfirmed(req)` with req being this format:  https://github.com/synonymdev/react-native-ldk/blob/f0320aee9e5fd64717727b6792f556bcce51e698/lib/src/utils/types.ts#L236

2023-06-30 07:34 UTC, Jasonvdb commented
Updated startup param check [here](https://github.com/synonymdev/react-native-ldk/pull/138/commits/dafea84d2281f1cda02db00a6b00a67016796085)

2023-06-30 15:40 UTC, bennyhodl commented
> > 
> Looks like the wrong format and native can't parse it. Are you calling `NativeLDK.setTxConfirmed` directly? If you are rather call `ldk.setTxConfirmed(req)` with req being this format:
> 
> https://github.com/synonymdev/react-native-ldk/blob/f0320aee9e5fd64717727b6792f556bcce51e698/lib/src/utils/types.ts#L236

ah i gave the wrong output.
```
{"header": "00000020139124db0d9d6146337157757b8312ea5356be78657ce2f49048a4079e000000cb2185d2859fdb659b6b15095f525ec217b451dbfaee47531d51f3072cf6cd988bbc9c64ae77031e6c6c0c00", 
"height": 195433, 
"txData": [{"pos": 1, "transaction": "87e7e6c3012e8b2ee49aa4006dd39a40b8ffea9fb29323a2ede71a85fa522f7e"}]}
```

2023-06-30 19:37 UTC, coreyphillips commented
Created PR [here](https://github.com/synonymdev/react-native-ldk/pull/140) with some updates that add signet to the networks object.

2023-06-30 19:47 UTC, coreyphillips submitted a review, later dismissed

2023-07-05 17:47 UTC, merged