Fix watchOutputs Loop
synonymdev/react-native-ldk pull request #223
Opened 2024-03-05 18:10 UTC by coreyphillips

This PR:
- Adds and tracks `confirmedWatchOutputs` to `lightning-manager.ts`.
- Increases timeout to `20000`ms.
- Updates `retrySyncOrReturnError` to return immediately if a `time-out` is detected.
- Replaces map with for of loop for Electrum queries.
- Adds `saveConfirmedWatchOutput` & `getConfirmedWatchOutputs` methods.
- Bumps version to `0.0.134`.
- Addresses #221

2024-03-05 20:31 UTC, ovitrif requested changes
Looks great!

Thanks for the fast fixing 🙇🏻 

The backup server fails to save the file, I tried after updating in `/backup-server/src/server.js` under 
```diff
const ldkLabels = [
    …
-   'channel_opened_with_custom_keys_manager'
+   'channel_opened_with_custom_keys_manager',
+   'confirmed_watch_outputs',
]
```
then it works 🚀

2024-03-05 20:41 UTC, coreyphillips commented
Ah nice catch, thanks! Updated [here](https://github.com/synonymdev/react-native-ldk/pull/223/commits/e7f09088181113a684d09a2f0b38fd104b2d597c).

2024-03-05 21:50 UTC, ovitrif approved these changes
All good 🚀

2024-03-06 07:16 UTC, Jasonvdb approved these changes

2024-03-06 07:17 UTC, merged